import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/public/css/global.css"
import AuthContextProvider from "./lib/auth_provider";
import WebSocketProvider from "./lib/ws_provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextProvider>
      <WebSocketProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </WebSocketProvider>
    </AuthContextProvider>
  );
}
