// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Main() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- TOP --><div id=\"top-container\" class=\"mt-2 h-16 w-full flex-shrink-0 px-2 py-1\"><div id=\"top-bar\" class=\"flex h-full w-full rounded-lg bg-[#332F4B] outline outline-2 outline-[#443F64]\"><!-- Contacts --><div id=\"contacts\" class=\"mx-1 flex h-full w-12 items-center justify-center\"><button id=\"menu\" class=\"flex h-10 w-10 cursor-pointer flex-col items-center justify-center space-y-1 rounded-lg bg-[#332F4B]  outline outline-[#443F64]\" hx-get=\"/open-modal?content=contacts\" hx-params=\"*\" hx-target=\"body\" hx-swap=\"beforeend\"><img class=\"h-8 w-8 object-scale-down\" src=\"../static/png/contact_icon.png\"></button></div><!-- Current Chat --><div id=\"current-chat\" class=\"flex h-full min-w-fit flex-1 items-center justify-center space-x-2 px-2\"><div id=\"icon\" class=\"h-10 w-10 rounded-full bg-[#443F64] outline outline-2 outline-[#443F64]\"><img class=\"h-full w-full object-scale-down\" src=\"../static/png/Linkup_logo.png\"></div><p id=\"contact-name\" class=\"text-gray-400\">*name*</p></div><!-- Settings --><div id=\"settings\" type=\"button\" class=\"mx-1 flex h-full w-12 items-center justify-center\"><button id=\"menu\" class=\"flex h-10 w-10 cursor-pointer flex-col items-center justify-center space-y-1 rounded-lg bg-[#332F4B]  outline outline-[#443F64]\" hx-get=\"/open-modal?content=settings\" hx-target=\"body\" hx-swap=\"beforeend\"><span class=\"h-1 w-6 rounded bg-[#443F64]\"></span> <span class=\"h-1 w-6 rounded bg-[#443F64]\"></span> <span class=\"h-1 w-6 rounded bg-[#443F64]\"></span></button></div></div></div><!-- MAIN --><div id=\"main-container\" class=\"flex h-full max-h-[calc(100dvh-4.5rem)] w-full flex-col p-2\"><div id=\"chat\" class=\"flex h-full w-full flex-grow flex-col-reverse overflow-auto rounded-lg bg-[#332F4B] p-2 outline outline-2 outline-[#443F64]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = UserMesage("hello world").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ContactMesage("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut condimentum quam. Donec aliquet non diam et commodo. Cras vehicula leo volutpat feugiat viverra. Morbi hendrerit mollis metus, non aliquet nisl pulvinarat. Aliquam eros sapien, egestas vitae molestie id, porta a mi. Proin non ex risus. Nulla laoreet volutpat odio").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = UserMesage("hello world").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ContactMesage("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut condimentum quam. Donec aliquet non diam et commodo. Cras vehicula leo volutpat feugiat viverra. Morbi hendrerit mollis metus, non aliquet nisl pulvinarat. Aliquam eros sapien, egestas vitae molestie id, porta a mi. Proin non ex risus. Nulla laoreet volutpat odio").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = UserMesage("hello world").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ContactMesage("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut condimentum quam. Donec aliquet non diam et commodo. Cras vehicula leo volutpat feugiat viverra. Morbi hendrerit mollis metus, non aliquet nisl pulvinarat. Aliquam eros sapien, egestas vitae molestie id, porta a mi. Proin non ex risus. Nulla laoreet volutpat odio").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = UserMesage("hello world").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = UserMesage("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut condimentum quam. Donec aliquet non diam et commodo. Cras vehicula leo volutpat feugiat viverra. Morbi hendrerit mollis metus, non aliquet nisl pulvinarat. Aliquam eros sapien, egestas vitae molestie id, porta a mi. Proin non ex risus. Nulla laoreet volutpat odio").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"flex flex-row\"><textarea placeholder=\"Type your message...\" id=\"input-area\" name=\"input-area\" class=\"mt-3 max-h-20 w-full resize-none overflow-y-scroll rounded-lg bg-[#332F4B] p-2 text-gray-50 outline outline-2 outline-[#443F64]\" rows=\"1\" oninput=\"this.style.height = &#39;&#39;; this.style.height = this.scrollHeight + &#39;px&#39;;\"></textarea><div class=\"ml-2 flex h-10 w-10 flex-shrink-0 items-center justify-center self-end\"><button type=\"button\" class=\"flex h-8 w-8\" hx-post=\"/send\" hx-include=\"#input-area\" hx-trigger=\"click, keydown[key==&#39;Enter&#39;] from:#input-area\" hx-swap=\"afterbegin\" hx-target=\"#chat\" hx-on::after-request=\"const textarea = document.getElementById(&#39;input-area&#39;);\n                  textarea.value = &#39;&#39;;\n                  textarea.style.height = &#39;&#39;;\n                  textarea.rows = 1;\"><img class=\"h-full w-full object-scale-down\" src=\"../static/png/send_icon.png\"></button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SettingsContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"mx-12 flex h-auto w-dvw max-w-screen-md flex-col space-y-4 rounded-lg bg-[#332F4B] p-4 outline outline-2 outline-[#443F64]\"><div class=\"flex h-10 w-full\"><h2 class=\"text-gray-400\">Settings</h2><div class=\"flex h-full flex-1\"></div><button class=\"flex text-gray-400 hover:text-gray-500\" hx-delete=\"/delete\" hx-target=\"#modal\" hx-swap=\"outerHTML\"><svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button></div><button class=\"flex h-10 w-full items-center justify-center rounded-lg bg-[#332F4B] outline outline-4 outline-[#443F64]\"><p class=\"text-white\">Change nickname</p></button> <button class=\"flex h-10 w-full items-center justify-center rounded-lg bg-[#332F4B] outline outline-4 outline-[#443F64]\"><p class=\"text-white\">Theme</p></button> <button class=\"flex h-10 w-full items-center justify-center rounded-lg bg-red-600 outline outline-4 outline-red-700\"><p class=\"text-white\">Logout</p></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ContactsContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"mx-12 flex h-auto w-dvw max-w-screen-md flex-col space-y-4 rounded-lg bg-[#332F4B] p-4 outline outline-2 outline-[#443F64]\"><div class=\"flex h-10 w-full\"><h2 class=\"text-gray-400\">Contacts</h2><div class=\"flex h-full flex-1\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Modal(content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div id=\"modal\" class=\"fixed inset-0 flex items-center justify-center bg-black bg-opacity-60 duration-300 animate-in fade-in\"><!-- Content -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- Click outside to close --><div class=\"fixed inset-0 -z-10\" hx-delete=\"/delete\" hx-target=\"#modal\" hx-swap=\"outerHTML\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div id=\"container\" class=\"flex h-dvh w-screen flex-col items-center justify-center align-middle\"><div id=\"login-container\" class=\"flex h-auto w-96 flex-col justify-center space-y-4 rounded-xl bg-[#332F4B] p-4 align-middle\"><div id=\"user-input\" class=\"flex flex-col space-y-4\"><input placeholder=\"email\" type=\"email\" id=\"element\" class=\"flex h-16 w-full rounded-xl bg-[#332F4B] pl-4 text-gray-50 placeholder-gray-400 outline outline-2 outline-[#443F64]\"> <input placeholder=\"password\" type=\"password\" id=\"element\" class=\"flex h-16 w-full rounded-xl bg-[#332F4B] pl-4 text-gray-50 placeholder-gray-400 outline outline-2 outline-[#443F64]\"> <button id=\"element\" class=\"flex h-16 w-full items-center justify-center rounded-xl border border-gray-300 bg-white shadow-md hover:bg-gray-100\"><img src=\"../static/png/google.png\" alt=\"Google Logo\" class=\"mr-3 h-8 w-8 object-scale-down\"><p class=\"text-base font-semibold tracking-wide text-black\">Sign in with Google</p></button></div><div id=\"login\" class=\"flex w-full flex-row space-x-4\"><a href=\"/\" class=\"flex h-16 w-full\"><button type=\"button\" class=\"flex h-auto w-full items-center justify-center rounded-xl bg-blue-600 align-middle\"><p class=\"text-base font-semibold tracking-wide text-white\">Login</p></button></a> <button hx-get=\"/register\" hx-swap=\"outerHTML\" hx-target=\"#container\" type=\"button\" class=\"flex h-16 w-full items-center justify-center rounded-xl bg-blue-600 align-middle\"><p class=\"text-base font-semibold tracking-wide text-white\">Register</p></button></div><div class=\"hidden h-16 w-16 bg-red-600 duration-500 animate-in fade-in sm:flex\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div id=\"container\" class=\"flex h-dvh w-screen flex-col items-center justify-center align-middle\"><div id=\"register-container\" class=\"flex h-auto w-96 flex-col justify-center space-y-4 rounded-xl bg-[#332F4B] p-4 align-middle\"><div id=\"user-input\" class=\"flex flex-col space-y-4\"><input placeholder=\"name\" type=\"text\" id=\"element\" class=\"flex h-16 w-full rounded-xl bg-[#332F4B] pl-4 text-gray-50 placeholder-gray-400 outline outline-2 outline-[#443F64]\"> <input placeholder=\"email\" type=\"email\" id=\"element\" class=\"flex h-16 w-full rounded-xl bg-[#332F4B] pl-4 text-gray-50 placeholder-gray-400 outline outline-2 outline-[#443F64]\"> <input placeholder=\"password\" type=\"password\" id=\"element\" class=\"flex h-16 w-full rounded-xl bg-[#332F4B] pl-4 text-gray-50 placeholder-gray-400 outline outline-2 outline-[#443F64]\"></div><a hx-get=\"/login\" hx-target=\"#container\" hx-swap=\"outerHTML\" class=\"cursor-pointer self-start text-sm text-blue-400 hover:underline\">Back to Login</a> <button type=\"button\" class=\"flex h-16 w-full items-center justify-center rounded-xl bg-blue-600 align-middle\"><p class=\"text-base font-semibold tracking-wide text-white\">Register</p></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
